In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# Creating Series Objects

In [ ]:
s = pd.Series([0, 1, 1, 2, 3, 5, 8])
print(s)

0    0
1    1
2    1
3    2
4    3
5    5
6    8
dtype: int64


In [ ]:
s = pd.Series([0.0, 1, 1, 2, 3, 5, 8])
print(s)

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    5.0
6    8.0
dtype: float64


In [ ]:
print(s.values)   # Iterable
print(s.index)    # Iterable

[0. 1. 1. 2. 3. 5. 8.]
RangeIndex(start=0, stop=7, step=1)


In [ ]:
for i in zip(s.index, s.values):
  print(i)

(0, 0.0)
(1, 1.0)
(2, 1.0)
(3, 2.0)
(4, 3.0)
(5, 5.0)
(6, 8.0)


In [ ]:
mars = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])
print(mars)

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64


In [ ]:
print(mars['mass'])
print(mars['diameter'])

0.33
57.9


In [ ]:
print(mars.mass)

0.33


In [ ]:
arr = np.random.randint(0, 10, 10)
ind = np.arange(10, 20)
print(arr, ind)

[1 7 2 3 8 5 3 3 3 4] [10 11 12 13 14 15 16 17 18 19]


In [ ]:
rand_series = pd.Series(arr, index=ind)
print(rand_series)

10    1
11    7
12    2
13    3
14    8
15    5
16    3
17    3
18    3
19    4
dtype: int64


In [ ]:
# mars = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])
d = {}
d['mass'] = 0.33
d['diameter'] = 57.9
d['dayLength'] = 4.2226

print(d)

{'mass': 0.33, 'diameter': 57.9, 'dayLength': 4.2226}


In [ ]:
mars = pd.Series(d)
print(mars)

mass          0.3300
diameter     57.9000
dayLength     4.2226
dtype: float64


In [ ]:
mars = pd.Series(d, index=['mass', 'dayLength'])     # index for filtering out
print(mars)

mass         0.3300
dayLength    4.2226
dtype: float64


# iloc and loc

In [ ]:
s = pd.Series([0.0, 1, 1, 2, 3, 5, 8], index=[1, 2, 3, 4 ,5, 6, 7])
print(s)

1    0.0
2    1.0
3    1.0
4    2.0
5    3.0
6    5.0
7    8.0
dtype: float64


In [ ]:
print(s.loc[4])
print(s.iloc[4])  

2.0
3.0


In [ ]:
mars = pd.Series([0.33, 57.9, 4222.6], index=['mass', 'diameter', 'dayLength'])
print(mars)

mass            0.33
diameter       57.90
dayLength    4222.60
dtype: float64


In [ ]:
print(mars.loc['mass'])
print(mars.iloc[0])  
print(mars.iloc[-1]) 

0.33
0.33
4222.6


In [ ]:
print("*"*10, "SLICING", "*"*10)
print(mars.iloc[0:2])   

********** SLICING **********
mass         0.33
diameter    57.90
dtype: float64


In [ ]:
print(mars.iloc[0:1]) 
print(mars.loc['mass':'diameter']) 

mass    0.33
dtype: float64
mass         0.33
diameter    57.90
dtype: float64


# Operations

In [ ]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])
print(mass)

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64


In [ ]:
print(mass.loc['Earth'])
print(mass.iloc[2])

5.97
5.97


In [ ]:
print(mass.loc['Earth': 'Neptune'])

Earth         5.970
Mars          0.642
Jupiter    1898.000
Saturn      568.000
Uranus       86.800
Neptune     102.000
dtype: float64


In [ ]:
print(mass.iloc[2: 7])

Earth         5.970
Mars          0.642
Jupiter    1898.000
Saturn      568.000
Uranus       86.800
dtype: float64


In [ ]:
# creting slices based on conditions
mass > 100

Mercury    False
Venus      False
Earth      False
Mars       False
Jupiter     True
Saturn      True
Uranus     False
Neptune     True
Pluto      False
dtype: bool

In [ ]:
mass[mass > 100]

Jupiter    1898.0
Saturn      568.0
Neptune     102.0
dtype: float64

In [ ]:
mass[(mass > 100) & (mass < 600)]

Saturn     568.0
Neptune    102.0
dtype: float64

In [ ]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64

In [ ]:
mass * 2             # mass as numpy array and broadcasting  (8,) & (1,)

Mercury       0.6600
Venus         9.7400
Earth        11.9400
Mars          1.2840
Jupiter    3796.0000
Saturn     1136.0000
Uranus      173.6000
Neptune     204.0000
Pluto         0.0292
dtype: float64

In [ ]:
mass / 10

Mercury      0.03300
Venus        0.48700
Earth        0.59700
Mars         0.06420
Jupiter    189.80000
Saturn      56.80000
Uranus       8.68000
Neptune     10.20000
Pluto        0.00146
dtype: float64

In [ ]:
print(np.mean(mass))    # mean is higher beacause of outliers
print(np.median(mass))
print(np.amin(mass))
print(np.amax(mass))

296.29184444444445
5.97
0.0146
1898.0


In [ ]:
mass + mass

Mercury       0.6600
Venus         9.7400
Earth        11.9400
Mars          1.2840
Jupiter    3796.0000
Saturn     1136.0000
Uranus      173.6000
Neptune     204.0000
Pluto         0.0292
dtype: float64

In [ ]:
mass - mass

Mercury    0.0
Venus      0.0
Earth      0.0
Mars       0.0
Jupiter    0.0
Saturn     0.0
Uranus     0.0
Neptune    0.0
Pluto      0.0
dtype: float64

In [ ]:
big_mass = mass[mass > 100]
print(big_mass)

Jupiter    1898.0
Saturn      568.0
Neptune     102.0
dtype: float64


In [ ]:
new_mass = mass + big_mass
print(new_mass)

Earth         NaN
Jupiter    3796.0
Mars          NaN
Mercury       NaN
Neptune     204.0
Pluto         NaN
Saturn     1136.0
Uranus        NaN
Venus         NaN
dtype: float64


In [ ]:
pd.isnull(new_mass)

Earth       True
Jupiter    False
Mars        True
Mercury     True
Neptune    False
Pluto       True
Saturn     False
Uranus      True
Venus       True
dtype: bool

In [ ]:
new_mass[~pd.isnull(new_mass)]     # ~ other operator

Jupiter    3796.0
Neptune     204.0
Saturn     1136.0
dtype: float64

In [ ]:
# Add new element
mass['Moon'] = 0.7346

In [ ]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
Moon          0.7346
dtype: float64

In [ ]:
# delete an element
mass.drop(['Pluto'])

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Moon          0.7346
dtype: float64

# Task 1

Collect numbers for the diameterof these planets and store it as a Series object.
Then given these two objects mass, diameter compute the desity of each planet

In [ ]:
diameter = pd.Series([4479, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370],
                 index=['Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

In [ ]:
 density = pd.Series([])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """Entry point for launching an IPython kernel.


In [ ]:
print(density)

Series([], dtype: float64)


In [ ]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
Moon          0.7346
dtype: float64

In [ ]:
diameter

Mercury      4479
Venus       12104
Earth       12756
Moon         3475
Mars         6792
Jupiter    142984
Saturn     120536
Uranus      51118
Neptune     49528
Pluto        2370
dtype: int64

In [ ]:
for planet in mass.index:
  density[planet] = mass[planet] / (np.pi * diameter[planet] * diameter[planet] * diameter[planet] / 6)

In [ ]:
print(density)

Mercury    7.014103e-12
Venus      5.244977e-12
Earth      5.493286e-12
Mars       3.913302e-12
Jupiter    1.240039e-12
Saturn     6.194402e-13
Uranus     1.241079e-12
Neptune    1.603427e-12
Pluto      2.094639e-12
Moon       3.343396e-11
dtype: float64


In [ ]:
# series are numpy arrays
# the indices of both the series should match in order to perform operation (mass and diameter)
density = mass / (np.pi * np.power(diameter, 3) / 6)

In [ ]:
density

Earth      5.493286e-12
Jupiter    1.240039e-12
Mars       3.913302e-12
Mercury    7.014103e-12
Moon       3.343396e-11
Neptune    1.603427e-12
Pluto      2.094639e-12
Saturn     6.194402e-13
Uranus     1.241079e-12
Venus      5.244977e-12
dtype: float64

In [ ]:
mass['PlanetX'] = 6

In [ ]:
density = mass / (np.pi * np.power(diameter, 3) / 6)

In [ ]:
density

Earth      5.493286e-12
Jupiter    1.240039e-12
Mars       3.913302e-12
Mercury    7.014103e-12
Moon       3.343396e-11
Neptune    1.603427e-12
PlanetX             NaN
Pluto      2.094639e-12
Saturn     6.194402e-13
Uranus     1.241079e-12
Venus      5.244977e-12
dtype: float64

## Task 2

Given the density series replace all values which NaNs with the mean density of the planet

In [ ]:
density_mean = np.mean(density)

for i in density.index:
  if pd.isnull(density[i]):
    density[i] = density_mean

print(density)

Earth      5.493286e-12
Jupiter    1.240039e-12
Mars       3.913302e-12
Mercury    7.014103e-12
Moon       3.343396e-11
Neptune    1.603427e-12
PlanetX    6.189826e-12
Pluto      2.094639e-12
Saturn     6.194402e-13
Uranus     1.241079e-12
Venus      5.244977e-12
dtype: float64


In [ ]:
density[pd.isnull(density)] = np.mean(density)
print(density)

Earth      5.493286e-12
Jupiter    1.240039e-12
Mars       3.913302e-12
Mercury    7.014103e-12
Moon       3.343396e-11
Neptune    1.603427e-12
PlanetX    6.189826e-12
Pluto      2.094639e-12
Saturn     6.194402e-13
Uranus     1.241079e-12
Venus      5.244977e-12
dtype: float64


## Task 3:
 Compare Dictionary with series


*   Checking if some key is present
*   Summing values
*   Computing std



In [ ]:
my_dict = {}
N = 1000000
for i in range(N):
  my_dict[i] = i%10

In [ ]:
my_series = pd.Series(my_dict)

In [ ]:
M = 10000

In [ ]:
arr = np.random.randint(0, N, M)

In [ ]:
%%timeit
for i in arr:
  i in my_dict

100 loops, best of 3: 9.37 ms per loop


In [ ]:
%%timeit
for i in arr:
  i in my_series

100 loops, best of 3: 12.8 ms per loop


In [ ]:
%%timeit
sum(my_dict.values())

100 loops, best of 3: 6.89 ms per loop


In [ ]:
%%timeit
np.sum(my_series)

1000 loops, best of 3: 868 µs per loop


In [ ]:
%%timeit
mean = sum(my_dict.values()) / N
variance = sum([(x-mean)**2 for x in my_dict.values()])
std = variance ** 0.5

10 loops, best of 3: 162 ms per loop


In [ ]:
%%timeit
np.std(my_series)

100 loops, best of 3: 3.55 ms per loop


# Case-Study: NIFTY

In [2]:
nifty = pd.read_csv("/content/nifty-200623-235920.csv", index_col=0).iloc[:, 0]

In [3]:
nifty.head()

Date
01-Jan-2019    10910.10
02-Jan-2019    10792.50
03-Jan-2019    10672.25
04-Jan-2019    10727.35
07-Jan-2019    10771.80
Name: Close, dtype: float64

In [4]:
print("mean: ", np.mean(nifty))
print("median: ", np.median(nifty))
print("std: ", np.std(nifty))

mean:  11432.632244897959
median:  11512.4
std:  453.2866947459807


What fraction of days the market close higher than the previous day's close

In [5]:
diff = nifty.iloc[1:].values - nifty.iloc[:-1].values 

In [6]:
diff

array([-1.1760e+02, -1.2025e+02,  5.5100e+01,  4.4450e+01,  3.0350e+01,
        5.3000e+01, -3.3550e+01, -2.6650e+01, -5.7350e+01,  1.4920e+02,
        3.5000e+00,  1.4900e+01,  1.7500e+00,  5.4900e+01, -3.9100e+01,
       -9.1250e+01,  1.8300e+01, -6.9250e+01, -1.1900e+02, -9.3500e+00,
       -4.0000e-01,  1.7915e+02,  6.2700e+01,  1.8600e+01,  2.2100e+01,
        1.2810e+02,  6.9500e+00, -1.2580e+02, -5.4800e+01, -5.7400e+01,
       -3.7750e+01, -4.7600e+01, -2.1650e+01, -8.3450e+01, -3.6600e+01,
        1.3110e+02,  5.4400e+01,  1.8000e+00,  8.8450e+01, -4.4800e+01,
       -2.8650e+01, -1.4150e+01,  7.1000e+01,  1.2395e+02,  6.5550e+01,
        5.2000e+00, -2.2800e+01,  1.3265e+02,  1.3315e+02,  4.0500e+01,
        1.5500e+00,  8.3600e+01,  3.5350e+01,  7.0200e+01, -1.1350e+01,
       -6.4150e+01, -1.0265e+02,  1.2900e+02, -3.8200e+01,  1.2495e+02,
        5.3900e+01,  4.5250e+01,  4.4050e+01, -6.9250e+01, -4.5950e+01,
        6.7950e+01, -6.1450e+01,  6.7450e+01, -8.7650e+01,  1.24

In [7]:
(nifty.iloc[1:].values - nifty.iloc[:-1].values ) > 0

array([False, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True, False,
       False, False,

In [8]:
np.sum((nifty.iloc[1:].values - nifty.iloc[:-1].values) > 0) 

129

In [ ]:
np.sum((nifty.iloc[1:].values - nifty.iloc[:-1].values) > 0) / len(nifty)

0.5265306122448979

1. Compute moving average of last 5 days
2. Subset the data to include only data for fridays

In [9]:
nifty.index[0]

'01-Jan-2019'

In [10]:
pd.Timestamp(nifty.index[0])

Timestamp('2019-01-01 00:00:00')

In [12]:
d = pd.Timestamp(nifty.index[0])
d.dayofweek

1

In [13]:
new_index = map(pd.Timestamp, nifty.index)

In [14]:
new_nifty = pd.Series(nifty, index=new_index)

In [16]:
new_nifty.index[0]

Timestamp('2019-01-01 00:00:00')

In [17]:
new_nifty.rolling('5d').mean()

2019-01-01    10910.100000
2019-01-02    10851.300000
2019-01-03    10791.616667
2019-01-04    10775.550000
2019-01-07    10723.800000
                  ...     
2019-12-24    12249.700000
2019-12-26    12201.283333
2019-12-27    12212.412500
2019-12-30    12209.400000
2019-12-31    12223.366667
Name: Close, Length: 245, dtype: float64

Look at friday data

In [21]:
dow = new_nifty.copy()
for i in dow.index:
  dow[i] = i.dayofweek

In [22]:
dow

2019-01-01    1.0
2019-01-02    2.0
2019-01-03    3.0
2019-01-04    4.0
2019-01-07    0.0
             ... 
2019-12-24    1.0
2019-12-26    3.0
2019-12-27    4.0
2019-12-30    0.0
2019-12-31    1.0
Name: Close, Length: 245, dtype: float64

In [23]:
new_nifty[dow == 4]

2019-01-04    10727.35
2019-01-11    10794.95
2019-01-18    10906.95
2019-01-25    10780.55
2019-02-01    10893.65
2019-02-08    10943.60
2019-02-15    10724.40
2019-02-22    10791.65
2019-03-01    10863.50
2019-03-08    11035.40
2019-03-15    11426.85
2019-03-22    11456.90
2019-03-29    11623.90
2019-04-05    11665.95
2019-04-12    11643.45
2019-04-26    11754.65
2019-05-03    11712.25
2019-05-10    11278.90
2019-05-17    11407.15
2019-05-24    11844.10
2019-05-31    11922.80
2019-06-07    11870.65
2019-06-14    11823.30
2019-06-21    11724.10
2019-06-28    11788.85
2019-07-05    11811.15
2019-07-12    11552.50
2019-07-19    11419.25
2019-07-26    11284.30
2019-08-02    10997.35
2019-08-09    11109.65
2019-08-16    11047.80
2019-08-23    10829.35
2019-08-30    11023.25
2019-09-06    10946.20
2019-09-13    11075.90
2019-09-20    11274.20
2019-09-27    11512.40
2019-10-04    11174.75
2019-10-11    11305.05
2019-10-18    11661.85
2019-10-25    11583.90
2019-11-01    11890.60
2019-11-08 

# DataFrames

## Creating dataframe objects

In [41]:
arr = np.random.randint(0, 10, (5, 3))

In [42]:
arr

array([[9, 2, 2],
       [5, 5, 6],
       [5, 0, 8],
       [0, 9, 8],
       [6, 1, 3]])

In [43]:
df = pd.DataFrame(arr)

In [44]:
df

0  1  2
0  9  2  2
1  5  5  6
2  5  0  8
3  0  9  8
4  6  1  3

In [46]:
print(df.values)
print(df.index)
print(df.columns)

[[9 2 2]
 [5 5 6]
 [5 0 8]
 [0 9 8]
 [6 1 3]]
RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=3, step=1)


In [49]:
df.index = ['R1', 'R2', 'R3', 'R4', 'R5']
df.columns = ['C1', 'C2', 'C3']

In [50]:
df

C1  C2  C3
R1   9   2   2
R2   5   5   6
R3   5   0   8
R4   0   9   8
R5   6   1   3

In [51]:
df.loc['R3', 'C2']

0

In [52]:
df.iloc[2, 1]

0

In [53]:
df.iloc[2:4, 1:3]

C2  C3
R3   0   8
R4   9   8

In [54]:
df.loc['R3':'R5', 'C2':'C3']

C2  C3
R3   0   8
R4   9   8
R5   1   3

In [58]:
print(type(df.iloc[0]))
df.iloc[0]

<class 'pandas.core.series.Series'>


C1    9
C2    2
C3    2
Name: R1, dtype: int64

In [59]:
print(type(df.iloc[:, 0]))
df.iloc[:, 0]

<class 'pandas.core.series.Series'>


R1    9
R2    5
R3    5
R4    0
R5    6
Name: C1, dtype: int64

In [60]:
df.T

R1  R2  R3  R4  R5
C1   9   5   5   0   6
C2   2   5   0   9   1
C3   2   6   8   8   3

In [41]:
def create_df(nRows, nCols, maxRand=10):
  arr = np.random.randint(0, maxRand, (nRows, nCols))
  df = pd.DataFrame(arr)
  df.index = ['R' + str(x) for x in range(1, nRows+1)]
  df.columns = ['C' + str(x) for x in range(1, nCols+1)]
  return df

In [65]:
create_df(5, 3)

C1  C2  C3
R1   0   6   3
R2   1   9   0
R3   8   3   3
R4   2   4   2
R5   8   1   5

In [54]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index=['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

diameter = pd.Series([4479, 12104, 12756, 3475, 6792, 142984, 120536, 51118, 49528, 2370],
                 index=['Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto'])

In [3]:
mass

Mercury       0.3300
Venus         4.8700
Earth         5.9700
Mars          0.6420
Jupiter    1898.0000
Saturn      568.0000
Uranus       86.8000
Neptune     102.0000
Pluto         0.0146
dtype: float64

In [4]:
diameter

Mercury      4479
Venus       12104
Earth       12756
Moon         3475
Mars         6792
Jupiter    142984
Saturn     120536
Uranus      51118
Neptune     49528
Pluto        2370
dtype: int64

In [5]:
df = pd.DataFrame({'mass': mass, 'diameter':diameter})

In [6]:
df

mass  diameter
Earth       5.9700     12756
Jupiter  1898.0000    142984
Mars        0.6420      6792
Mercury     0.3300      4479
Moon           NaN      3475
Neptune   102.0000     49528
Pluto       0.0146      2370
Saturn    568.0000    120536
Uranus     86.8000     51118
Venus       4.8700     12104

In [7]:
df['mass']

Earth         5.9700
Jupiter    1898.0000
Mars          0.6420
Mercury       0.3300
Moon             NaN
Neptune     102.0000
Pluto         0.0146
Saturn      568.0000
Uranus       86.8000
Venus         4.8700
Name: mass, dtype: float64

In [12]:
df['Earth']

KeyError: ignored

In [8]:
df['mass']['Earth']

5.97

In [9]:
df.mass.Earth

5.97

In [13]:
df.loc['Earth']

mass        5.970000e+00
diameter    1.275600e+04
pop         8.000000e+09
Name: Earth, dtype: float64

In [10]:
df['pop'] = 0
df

mass  diameter  pop
Earth       5.9700     12756    0
Jupiter  1898.0000    142984    0
Mars        0.6420      6792    0
Mercury     0.3300      4479    0
Moon           NaN      3475    0
Neptune   102.0000     49528    0
Pluto       0.0146      2370    0
Saturn    568.0000    120536    0
Uranus     86.8000     51118    0
Venus       4.8700     12104    0

In [11]:
df['pop']['Earth'] = 8000000000
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


mass  diameter         pop
Earth       5.9700     12756  8000000000
Jupiter  1898.0000    142984           0
Mars        0.6420      6792           0
Mercury     0.3300      4479           0
Moon           NaN      3475           0
Neptune   102.0000     49528           0
Pluto       0.0146      2370           0
Saturn    568.0000    120536           0
Uranus     86.8000     51118           0
Venus       4.8700     12104           0

In [17]:
df.loc[:, "mass"]

Earth         5.9700
Jupiter    1898.0000
Mars          0.6420
Mercury       0.3300
Moon             NaN
Neptune     102.0000
Pluto         0.0146
Saturn      568.0000
Uranus       86.8000
Venus         4.8700
Name: mass, dtype: float64

In [40]:
def create_mean_row(df):
  # df.loc["mean"] = [np.mean(df[col]) for col in df.columns]
  df.loc["mean"] = df.mean()
  return df

create_mean_row(df)

mass  diameter
Earth       5.970000   12756.0
Jupiter  1898.000000  142984.0
Mars        0.642000    6792.0
Mercury     0.330000    4479.0
Moon             NaN    3475.0
Neptune   102.000000   49528.0
Pluto       0.014600    2370.0
Saturn    568.000000  120536.0
Uranus     86.800000   51118.0
Venus       4.870000   12104.0
mean      296.291844   40614.2

In [35]:
# droping row and showing the change by using inplace
df.drop('mean', axis=0, inplace=True)

In [42]:
df = create_df(5, 3)
df

C1  C2  C3
R1   4   1   6
R2   9   8   0
R3   9   4   7
R4   1   9   4
R5   5   8   2

In [43]:
df.mean()    # calculating dataframe mean column wise efficiently

C1    5.6
C2    6.0
C3    3.8
dtype: float64

In [44]:
df.mean(axis=1)    # calculating dataframe mean row wise efficiently

R1    3.666667
R2    5.666667
R3    6.666667
R4    4.666667
R5    5.000000
dtype: float64

In [46]:
# Adding row and column mean to dataframe
df['Row_Mean'] = df.mean(axis=1)
df.loc['Col_Mean'] = df.mean()

df

C1   C2   C3  Row_Mean
R1        4.0  1.0  6.0  3.666667
R2        9.0  8.0  0.0  5.666667
R3        9.0  4.0  7.0  6.666667
R4        1.0  9.0  4.0  4.666667
R5        5.0  8.0  2.0  5.000000
Col_Mean  5.6  6.0  3.8  5.133333

In [49]:
# Other stats for dataframe
print(df.median())
print(df.min())
print(df.max())
print(df.quantile(0.25))

C1          5.300000
C2          7.000000
C3          3.900000
Row_Mean    5.066667
dtype: float64
C1          1.000000
C2          1.000000
C3          0.000000
Row_Mean    3.666667
dtype: float64
C1          9.000000
C2          9.000000
C3          7.000000
Row_Mean    6.666667
dtype: float64
C1          4.25
C2          4.50
C3          2.45
Row_Mean    4.75
Name: 0.25, dtype: float64


In [52]:
df.drop('Row_Mean', axis=1)

C1   C2   C3
R1        4.0  1.0  6.0
R2        9.0  8.0  0.0
R3        9.0  4.0  7.0
R4        1.0  9.0  4.0
R5        5.0  8.0  2.0
Col_Mean  5.6  6.0  3.8

In [53]:
df.describe()

C1       C2       C3  Row_Mean
count  6.000000  6.00000  6.00000  6.000000
mean   5.600000  6.00000  3.80000  5.133333
std    3.072458  3.03315  2.56125  1.002220
min    1.000000  1.00000  0.00000  3.666667
25%    4.250000  4.50000  2.45000  4.750000
50%    5.300000  7.00000  3.90000  5.066667
75%    8.150000  8.00000  5.50000  5.533333
max    9.000000  9.00000  7.00000  6.666667

In [55]:
planets = pd.DataFrame({'mass': mass, 'diameter':diameter})

In [56]:
planets.describe()

mass      diameter
count     9.000000      10.00000
mean    296.291844   40614.20000
std     627.786429   51572.38648
min       0.014600    2370.00000
25%       0.642000    5057.25000
50%       5.970000   12430.00000
75%     102.000000   50720.50000
max    1898.000000  142984.00000

# Working with planetary data

In [3]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'tips', 'titanic']


/usr/local/lib/python3.6/dist-packages/seaborn/utils.py:384: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 384 of the file /usr/local/lib/python3.6/dist-packages/seaborn/utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)


In [35]:
df = sns.load_dataset('planets')
print(df.shape)
df.head()

(1035, 6)


method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [6]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

### Go through each roe of the dataframe and delete it(drop)if any column is null

In [8]:
for r in df.index:
  for c in df.columns:
    if pd.isnull(df.loc[r, c]):
      df.drop(r, inplace=True)
      break

In [9]:
df.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [12]:
for i, r in df.iterrows():
  print(i)
  print(r)
  break

0
method            Radial Velocity
number                          1
orbital_period              269.3
mass                          7.1
distance                     77.4
year                         2006
Name: 0, dtype: object


In [14]:
for i, r in df.iterrows():
  print(pd.isnull(r))
  break

method            False
number            False
orbital_period    False
mass              False
distance          False
year              False
Name: 0, dtype: bool


In [15]:
for i, r in df.iterrows():
  print(pd.isnull(r).any())
  break

False


In [16]:
for i, r in df.iterrows():
  if pd.isnull(r).any():
    df.drop(i, inplace=True)

In [18]:
df.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [20]:
df.dropna(inplace=True)

In [21]:
df.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

### Filter and show onlythose rows which have planets that are found in the 2010s and method is 'radial velocity' and 'transit' and distance is larger than (75 percentile)

In [26]:
df_ = df.copy()
per_75 = df.distance.quantile(0.75)
for i, r in df_.iterrows():
  if r['year'] < 2010:
    df_.drop(i, inplace=True)
    continue
  if r['method'] != 'Radial Velocity' and r['method'] != 'Transit':
    df_.drop(i, inplace=True)
    continue
  if r['distance'] < per_75:
    df_.drop(i, inplace=True)
    continue

In [27]:
df_.describe()

number  orbital_period       mass    distance         year
count  50.000000       50.000000  50.000000   50.000000    50.000000
mean    1.300000      763.904808   3.322740  133.142600  2011.360000
std     0.505076      966.789870   3.648002   70.378699     1.120496
min     1.000000        2.703390   0.770000   65.620000  2010.000000
25%     1.000000      255.555000   1.325000   80.205000  2011.000000
50%     1.000000      550.500000   1.875000  121.070000  2011.000000
75%     2.000000      873.625000   3.400000  150.097500  2012.000000
max     3.000000     5584.000000  20.600000  354.000000  2014.000000

In [29]:
df_.head()

method  number  orbital_period   mass  distance  year
9   Radial Velocity       2          452.80   1.99     74.79  2010
10  Radial Velocity       2          883.00   0.86     74.79  2010
58  Radial Velocity       1          277.02   1.70     80.64  2013
63  Radial Velocity       1          305.50  20.60     92.51  2013
84  Radial Velocity       1          137.48   1.11    175.44  2013

In [33]:
df_ = df.copy()
df_ = df_[
   (df_['year'] >= 2010) &
   ((df_['method'] == 'Radial Velocity') | (df_['method'] == 'Transit')) &
   (df_['distance'] > per_75)
]

In [34]:
df_.describe()

number  orbital_period       mass    distance         year
count  50.000000       50.000000  50.000000   50.000000    50.000000
mean    1.300000      763.904808   3.322740  133.142600  2011.360000
std     0.505076      966.789870   3.648002   70.378699     1.120496
min     1.000000        2.703390   0.770000   65.620000  2010.000000
25%     1.000000      255.555000   1.325000   80.205000  2011.000000
50%     1.000000      550.500000   1.875000  121.070000  2011.000000
75%     2.000000      873.625000   3.400000  150.097500  2012.000000
max     3.000000     5584.000000  20.600000  354.000000  2014.000000

### Modify the method column to ave only the abbreviation of each method

In [37]:
df.method.unique()

array(['Radial Velocity', 'Imaging', 'Eclipse Timing Variations',
       'Transit', 'Astrometry', 'Transit Timing Variations',
       'Orbital Brightness Modulation', 'Microlensing', 'Pulsar Timing',
       'Pulsation Timing Variations'], dtype=object)

In [38]:
s = 'Radial Velocity'

In [40]:
s.split(' ')

['Radial', 'Velocity']

In [41]:
[x[0] for x in s.split(' ')]

['R', 'V']

In [42]:
''.join([x[0] for x in s.split(' ')])

'RV'

In [43]:
s = 'Orbital Brightness Modulation'
''.join([x[0] for x in s.split(' ')])

'OBM'

In [44]:
short_names = {}
for s in df.method.unique():
  short_names[s] = ''.join([x[0] for x in s.split(' ')])

In [45]:
print(short_names)

{'Radial Velocity': 'RV', 'Imaging': 'I', 'Eclipse Timing Variations': 'ETV', 'Transit': 'T', 'Astrometry': 'A', 'Transit Timing Variations': 'TTV', 'Orbital Brightness Modulation': 'OBM', 'Microlensing': 'M', 'Pulsar Timing': 'PT', 'Pulsation Timing Variations': 'PTV'}


In [47]:
for i, r in df.iterrows():
  df.loc[i, 'short_method'] = short_names.get(r['method'], r['method'])

In [48]:
df.head()

method  number  orbital_period   mass  distance  year short_method
0  Radial Velocity       1         269.300   7.10     77.40  2006           RV
1  Radial Velocity       1         874.774   2.21     56.95  2008           RV
2  Radial Velocity       1         763.000   2.60     19.84  2011           RV
3  Radial Velocity       1         326.030  19.40    110.62  2007           RV
4  Radial Velocity       1         516.220  10.50    119.47  2009           RV

In [2]:
df = sns.load_dataset('planets')

In [50]:
def shorten_names(s):
  return short_names.get(s, s)

In [51]:
df['short_method'] = df['method'].apply(shorten_names)

In [52]:
df.head()

method  number  orbital_period   mass  distance  year short_method
0  Radial Velocity       1         269.300   7.10     77.40  2006           RV
1  Radial Velocity       1         874.774   2.21     56.95  2008           RV
2  Radial Velocity       1         763.000   2.60     19.84  2011           RV
3  Radial Velocity       1         326.030  19.40    110.62  2007           RV
4  Radial Velocity       1         516.220  10.50    119.47  2009           RV

### Count the number of planets discovered for each method type 

1. **Split** the dataframe into smaller chunks(in case they should have the same method name)
2. **Apply** some functionin each smaller chunk (in this case it is the count function)
3. **Aggregate** the results from each chunk together

In [3]:
d = {}
for m in df.method.unique():
  d[m] = df[df.method == m]['method'].count()
  
print(d)

{'Radial Velocity': 553, 'Imaging': 38, 'Eclipse Timing Variations': 9, 'Transit': 397, 'Astrometry': 2, 'Transit Timing Variations': 4, 'Orbital Brightness Modulation': 3, 'Microlensing': 23, 'Pulsar Timing': 5, 'Pulsation Timing Variations': 1}


In [4]:
df.groupby('method')['method'].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: method, dtype: int64

In [5]:
d = {}
for m in df.method.unique():
  d[m] = df[df.method == m]['distance'].mean()
  
print(d)

{'Radial Velocity': 51.60020754716983, 'Imaging': 67.7159375, 'Eclipse Timing Variations': 315.36, 'Transit': 599.2980803571429, 'Astrometry': 17.875, 'Transit Timing Variations': 1104.3333333333333, 'Orbital Brightness Modulation': 1180.0, 'Microlensing': 4144.0, 'Pulsar Timing': 1200.0, 'Pulsation Timing Variations': nan}


In [6]:
df.groupby('method')['distance'].mean()

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

### Find out what fraction of planets have been found in the last decade (i.e., in 2010) across each method type

1. **Filter** the data for given condition (in this case planet found in last decade)
2. **Split** (in this case across method)
3. **Apply** (in this case just count)
4. **Aggregate** (to represent the final result)

In [10]:
# filtering           |# groubby        |# subsetting
df[df['year'] >= 2010].groupby('method')['method'].count()
                                                  # applying function

method
Astrometry                         2
Eclipse Timing Variations          6
Imaging                           18
Microlensing                      13
Orbital Brightness Modulation      3
Pulsar Timing                      1
Radial Velocity                  215
Transit                          335
Transit Timing Variations          4
Name: method, dtype: int64

In [16]:
df.groupby('method')['method'].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: method, dtype: int64

In [17]:
s_2010s = df[df['year'] >= 2010].groupby('method')['method'].count()
s_all_time = df.groupby('method')['method'].count()

In [18]:
s_2010s/s_all_time

method
Astrometry                       1.000000
Eclipse Timing Variations        0.666667
Imaging                          0.473684
Microlensing                     0.565217
Orbital Brightness Modulation    1.000000
Pulsar Timing                    0.200000
Pulsation Timing Variations           NaN
Radial Velocity                  0.388788
Transit                          0.843829
Transit Timing Variations        1.000000
Name: method, dtype: float64

# Task: Nifty 

### Find a dataset of Nifty numbers of 2018 to 2019- daily numbers open, close, high, low

In [2]:
!unzip /content/Nifty_csv_files-200628-122439.zip

Archive:  /content/Nifty_csv_files-200628-122439.zip
  inflating: NIFTY50_2019.csv        
  inflating: NIFTY50_2018.csv        
  inflating: NIFTYNext50_2019.csv    


In [3]:
nifty50_2018 = pd.read_csv("/content/NIFTY50_2018.csv")
nifty50_2018.head()

Date      Open      High       Low     Close
0  31 Dec 2018  10913.20  10923.55  10853.20  10862.55
1  28 Dec 2018  10820.95  10893.60  10817.15  10859.90
2  27 Dec 2018  10817.90  10834.20  10764.45  10779.80
3  26 Dec 2018  10635.45  10747.50  10534.55  10729.85
4  24 Dec 2018  10780.90  10782.30  10649.25  10663.50

In [4]:
nifty50_2018 = pd.read_csv("/content/NIFTY50_2018.csv", index_col=0)
nifty50_2018.head()

Open      High       Low     Close
Date                                               
31 Dec 2018  10913.20  10923.55  10853.20  10862.55
28 Dec 2018  10820.95  10893.60  10817.15  10859.90
27 Dec 2018  10817.90  10834.20  10764.45  10779.80
26 Dec 2018  10635.45  10747.50  10534.55  10729.85
24 Dec 2018  10780.90  10782.30  10649.25  10663.50

In [5]:
nifty50_2018.loc["31 Dec 2018"]

Open     10913.20
High     10923.55
Low      10853.20
Close    10862.55
Name: 31 Dec 2018, dtype: float64

In [6]:
nifty50_2018['Open']     # index is retained

Date
31 Dec 2018    10913.20
28 Dec 2018    10820.95
27 Dec 2018    10817.90
26 Dec 2018    10635.45
24 Dec 2018    10780.90
                 ...   
05 Jan 2018    10534.25
04 Jan 2018    10469.40
03 Jan 2018    10482.65
02 Jan 2018    10477.55
01 Jan 2018    10531.70
Name: Open, Length: 246, dtype: float64

In [7]:
nifty50_2019 = pd.read_csv("/content/NIFTY50_2019.csv", index_col=0)
nifty50_2019.head()

Open      High       Low     Close
Date                                               
31 Dec 2019  12247.10  12247.10  12151.80  12168.45
30 Dec 2019  12274.90  12286.45  12213.80  12255.85
27 Dec 2019  12172.90  12258.45  12157.90  12245.80
26 Dec 2019  12211.85  12221.55  12118.85  12126.55
24 Dec 2019  12269.25  12283.70  12202.10  12214.55

In [8]:
# Combine nifty50_2018 and nifty50_2019
nifty50 = pd.concat([nifty50_2018, nifty50_2019])

In [9]:
niftynext50_2019 = pd.read_csv("/content/NIFTYNext50_2019.csv", index_col=0)
niftynext50_2019.head()

Open      High       Low     Close
Date                                               
31 Dec 2019  28495.00  28549.50  28270.25  28307.55
30 Dec 2019  28528.95  28612.95  28406.70  28484.85
27 Dec 2019  28354.50  28500.25  28319.90  28476.80
26 Dec 2019  28409.10  28435.25  28259.75  28280.25
24 Dec 2019  28423.70  28430.40  28318.75  28382.85

In [10]:
nifty_2019 = pd.concat([nifty50_2019, niftynext50_2019], axis=1)

In [11]:
nifty_2019.head()

Open      High       Low  ...      High       Low     Close
Date                                       ...                              
31 Dec 2019  12247.10  12247.10  12151.80  ...  28549.50  28270.25  28307.55
30 Dec 2019  12274.90  12286.45  12213.80  ...  28612.95  28406.70  28484.85
27 Dec 2019  12172.90  12258.45  12157.90  ...  28500.25  28319.90  28476.80
26 Dec 2019  12211.85  12221.55  12118.85  ...  28435.25  28259.75  28280.25
24 Dec 2019  12269.25  12283.70  12202.10  ...  28430.40  28318.75  28382.85

[5 rows x 8 columns]

In [37]:
nifty_2019 = pd.concat([nifty50_2019, niftynext50_2019], axis=1,
                       keys=['nifty50', 'niftynext50'])
nifty_2019.head()

nifty50                      ... niftynext50                   
                 Open      High       Low  ...         Low     Close Volatile
Date                                       ...                               
31 Dec 2019  12247.10  12247.10  12151.80  ...    28270.25  28307.55    False
30 Dec 2019  12274.90  12286.45  12213.80  ...    28406.70  28484.85    False
27 Dec 2019  12172.90  12258.45  12157.90  ...    28319.90  28476.80    False
26 Dec 2019  12211.85  12221.55  12118.85  ...    28259.75  28280.25    False
24 Dec 2019  12269.25  12283.70  12202.10  ...    28318.75  28382.85    False

[5 rows x 10 columns]

In [13]:
nifty_2019['nifty50'].loc['31 Dec 2019']

Open     12247.10
High     12247.10
Low      12151.80
Close    12168.45
Name: 31 Dec 2019, dtype: float64

1. In 2019, in how many days was the NIFTY50 volatile(high > 105% of low)
2. In 2019, in how many days was the NIFTYNEXT50 volatile(high > 105% of low)
3. In 2019, how many days belong to four classes NIFTY50 volatile/ non-volatile and NIFTYNEXT50 volatile/ non-volatile
4. Compute the mean, median, mode, std, var of closing value of each weekday in NIFTY50 for 2019
5. Compute the mean, median, mode, std, var of closing value of each month in NIFTY50 for 2019
6. On the days in which NIFTY50 closed higher than the open, what was thw mean of (close-open) for NIFTYNext50
7. In 2019, how many days had the day's high lower than the previous day's low in NIFTY50
8. In 2019, on how many days did the day's close exceed the 30 day mooving average in NIFTY50(exclude first month)


In [ ]:
# In 2019, in how many days was the NIFTY50 volatile(high > 105% of low)

nifty50_2019['Volatile'] = nifty50_2019['High'] > (nifty50_2019['Low'] * 1.05)
print(nifty50_2019.Volatile.value_counts())

# In 2019, in how many days was the NIFTYNEXT50 volatile(high > 105% of low)
niftynext50_2019['Volatile'] = niftynext50_2019['High'] > (niftynext50_2019['Low'] * 1.05)
print(niftynext50_2019.Volatile.value_counts())

False    244
True       1
Name: Volatile, dtype: int64
False    244
True       1
Name: Volatile, dtype: int64


In [ ]:
# In 2019, how many days belong to four classes NIFTY50 volatile/ non-volatile and NIFTYNEXT50 volatile/ non-volatile


In [ ]:
# Compute the mean, median, mode, std, var of closing value of each weekday in NIFTY50 for 2019
